### ISSUE TITLE
Including from another flake as an overlay

### ISSUE THREAD

**Issue by ghost** [wiltaylor/neovim-flake#1]
Thank you for the nice flake. I am trying to include this as an overlay to my dotfiles flake but it does not work :/
```sh
$ nix build
error: attempt to call something which is not a function but a set

       at /nix/store/3ywpdklg464mrjq5bzysxdbz10475li3-source/lib/fixed-points.nix:69:67:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                   ^
           70|
(use '--show-trace' to show detailed location information)
```
It runs when I `nix run github:wiltaylor/neovim-flake` though. Do you have any idea or suggestion?

**Comment by wiltaylor** [comment]
Thanks, yeah I have been running into a similar problem. I will post back here once i fix it :)

**Comment by wiltaylor** [comment]
Ok actually a pretty easy fix. Because i am using flake-utils in this flake you need to add the architecture when referencing the overlay.

So `neovim-flake.overlays.x86_64-linux` instead of just `neovim-flake.overlays`.

There appears to be something in the latest version of nix packages though that is breaking plugins though so I am now looking into that :/.

**Comment by wiltaylor** [comment]
Appears to have been created by https://github.com/NixOS/nixpkgs/commit/4a860879ea76c2be86a696cb885cc51bfe8f61fa and is also impacting neovitality.

**Comment by wiltaylor** [comment]
Resolved issues by breaking out wrapper into flake instead of the one in nix packages that is a bit unstable at the moment.
